server:
  port: 7001
eureka:
  instance:
    hostname: server-dev
    prefer-ip-address: false
    metadata-map:
      name: eureka-register-center-dev
  client:
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: true
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: true
    service-url:
      defaultZone: http://server-prod:7002/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000