spring:
  application:
    name: register
server:
  port: 7003
eureka:
  instance:
    hostname: server-test
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://server-dev:7001/eureka/,http://server-prod:7002/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000