server:
  port: 8088
mybatis-plus:
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    worker-id: 0
    datacenter-id: 0
  mapper-locations: classpath*:/mapper/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail-user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gepoint
    type: com.zaxxer.hikari.HikariDataSource